# This demonstration of containerbuddy has port mappings so we can use it
# on docker-machine locally.

consul:
    image: progrium/consul:latest
    command: >
      -server
      -bootstrap-expect 1
      -ui-dir /ui
    mem_limit: 256m
    expose:
    - 53
    - 8300
    - 8301
    - 8302
    - 8400
    - 8500
    - 8600
    ports:
    - 8500:8500
    restart: always

nginx:
    build: nginx/
    mem_limit: 512m
    expose:
    - 80
    links:
    - consul:consul
    restart: always
    command: >
      /opt/containerbuddy/containerbuddy
      -config file:///opt/containerbuddy/nginx.json
      nginx -g "daemon off;"

cloudflare:
    build: cloudflare/
    mem_limit: 128m
    links:
    - consul:consul
    restart: always
    env_file: .env
    command: >
      /opt/containerbuddy/containerbuddy
      -config file:///opt/containerbuddy/cloudflare.json
